project_id = "GitBoost"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://gitboost.dev"]
jwt_expiry = 3600

[auth.external.github]
enabled = true
client_id = "YOUR_GITHUB_CLIENT_ID"
secret = "YOUR_GITHUB_SECRET"

[functions]
[functions."grant-achievement"]
verify_jwt = true
